#!/usr/bin/env python3
"""
Job Searcher - Automated Job Search Email System
"""
import os
import yaml
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime
from openai import OpenAI
from dotenv import load_dotenv

# Load environment variables
load_dotenv()


class JobSearcher:
    """Main class for job search automation"""
    
    def __init__(self, config_path='config.yaml'):
        """Initialize the job searcher system with configuration"""
        self.config = self.load_config(config_path)
        self.openai_client = OpenAI(api_key=os.getenv('OPENAI_API_KEY'))
        
    def load_config(self, config_path):
        """Load configuration from YAML file"""
        try:
            with open(config_path, 'r') as f:
                return yaml.safe_load(f)
        except FileNotFoundError:
            raise Exception(f"Configuration file not found: {config_path}")
    
    def search_jobs(self):
        """Use ChatGPT with web search to find real-time job opportunities"""
        prompt = self.config.get('job_search_prompt', '')
        
        if not prompt:
            raise ValueError("No job search prompt configured")
        
        try:
            # Use Responses API with web_search tool for real-time job search
            response = self.openai_client.responses.create(
                model=self.config.get('openai_model', 'gpt-4'),
                tools=[{"type": "web_search"}],
                input=prompt
            )
            
            return response.output_text
        except Exception as e:
            raise Exception(f"Error calling OpenAI API: {str(e)}")
    
    def format_email(self, job_results):
        """Format job results into an HTML email"""
        today = datetime.now().strftime("%Y-%m-%d")
        
        html = f"""
        <html>
            <head>
                <style>
                    body {{ font-family: Arial, sans-serif; line-height: 1.6; color: #333; }}
                    h1 {{ color: #2c3e50; }}
                    h2 {{ color: #34495e; margin-top: 20px; }}
                    .header {{ background-color: #3498db; color: white; padding: 20px; }}
                    .content {{ padding: 20px; }}
                    .footer {{ background-color: #ecf0f1; padding: 10px; text-align: center; font-size: 12px; color: #7f8c8d; }}
                    .job-content {{ white-space: pre-wrap; }}
                </style>
            </head>
            <body>
                <div class="header">
                    <h1>Your Daily Job Recommendations</h1>
                    <p>Date: {today}</p>
                </div>
                <div class="content">
                    <div class="job-content">
{job_results}
                    </div>
                </div>
                <div class="footer">
                    <p>This email was automatically generated by Job Searcher</p>
                </div>
            </body>
        </html>
        """
        
        return html
    
    def send_email(self, html_content):
        """Send the formatted email"""
        email_config = self.config.get('email', {})
        
        # Get email configuration
        smtp_server = email_config.get('smtp_server', os.getenv('SMTP_SERVER'))
        
        # Handle SMTP port with proper validation
        smtp_port = email_config.get('smtp_port')
        if smtp_port is None:
            try:
                smtp_port = int(os.getenv('SMTP_PORT', '587'))
            except (ValueError, TypeError):
                smtp_port = 587
        
        sender_email = email_config.get('sender_email', os.getenv('SENDER_EMAIL'))
        sender_password = email_config.get('sender_password', os.getenv('APP_PASSWORD'))
        recipient_email = email_config.get('recipient_email', os.getenv('RECIPIENT_EMAIL'))
        
        # Strip whitespace from credentials (handles newlines and spaces)
        if sender_email:
            sender_email = sender_email.strip()
        if sender_password:
            sender_password = sender_password.strip()
        if recipient_email:
            recipient_email = recipient_email.strip()
        
        if not all([smtp_server, sender_email, sender_password, recipient_email]):
            raise ValueError("Missing email configuration. Please check config.yaml or environment variables.")
        
        # Create message
        message = MIMEMultipart('alternative')
        message['Subject'] = f"Daily Job Recommendations - {datetime.now().strftime('%Y-%m-%d')}"
        message['From'] = sender_email
        message['To'] = recipient_email
        
        # Attach HTML content
        html_part = MIMEText(html_content, 'html')
        message.attach(html_part)
        
        # Send email
        try:
            with smtplib.SMTP(smtp_server, smtp_port) as server:
                server.starttls()
                server.login(sender_email, sender_password)
                server.send_message(message)
            print(f"Email sent successfully to {recipient_email}")
        except Exception as e:
            raise Exception(f"Error sending email: {str(e)}")
    
    def run(self):
        """Execute the complete job search and email workflow"""
        print(f"Starting job search at {datetime.now()}")
        
        try:
            # Search for jobs using ChatGPT
            print("Searching for jobs...")
            job_results = self.search_jobs()
            
            # Format results as email
            print("Formatting email...")
            html_content = self.format_email(job_results)
            
            # Send email
            print("Sending email...")
            self.send_email(html_content)
            
            print("Job search completed successfully!")
        except Exception as e:
            print(f"Error: {str(e)}")
            raise


def main():
    """Main entry point"""
    job_searcher = JobSearcher()
    job_searcher.run()


if __name__ == "__main__":
    main()
